<?php require_once './templates/blocs/header.phtml'; ?>

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <table class="table table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Code</th>
                        <th>Nom</th>
                        <th>Nom (Capitales)</th>
                        <th>SLUG</th>
                        <th>Soundex</th>
                        <th>Soundex attendu</th>
                        <th>E.mail</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($departements as $departement) : ?>
                    <tr class="<?=$departement['classe']?>">
                        <td class=""><?=$departement['departement_id']?></td>
                        <td class="<?=$departement['col_classes']['departement_code']?>"><?=$departement['departement_code']?></td>
                        <td class="<?=$departement['col_classes']['departement_nom']?>"><?=$departement['departement_nom']?></td>
                        <td class="<?=$departement['col_classes']['departement_nom_uppercase']?>"><?=$departement['departement_nom_uppercase']?></td>
                        <td class="<?=$departement['col_classes']['departement_slug']?>"><?=$departement['departement_slug']?></td>
                        <td class="<?=$departement['col_classes']['departement_nom_soundex']?>"><?=$departement['departement_nom_soundex']?></td>
                        <td class=""><?=$departement['soundex_preview']?></td>
                        <td class="<?=$departement['col_classes']['departement_email']?>"><?=$departement['departement_email']?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php require_once './templates/blocs/footer.phtml'; ?>


